{ 

  "swagger": "2.0", 

  "info": { 

    "title": "<sample title>", 

    "version": "1.0", 

    "x-ms-keywords": "<your keywords of connector name go here>" 

  }, 

  "paths": { 

    "<your API path goes here>": { 

      "get": { 

        "tags": [ 

          "Documents" 

        ], 

        "operationId": "scp-get-related-activities", 

        "produces": [ 

          "application/json" 

        ], 

        "parameters": [ 

          { 

            "in": "query", 

            "name": "recordType", 

            "required": true, 

            "type": "string", 

            "enum": [ 

              "account", 

              "opportunity" 

            ] 

          }, 

          { 

            "in": "query", 

            "name": "recordId", 

            "required": true, 

            "type": "string" 

          }, 

          { 

            "in": "query", 

            "name": "startDateTime", 

            "type": "string", 

            "format": "date-time" 

          }, 

          { 

            "in": "query", 

            "name": "endDateTime", 

            "type": "string", 

            "format": "date-time" 

          }, 

          { 

            "in": "query", 

            "name": "top", 

            "type": "integer", 

            "format": "int32" 

          }, 

          { 

            "in": "query", 

            "name": "skip", 

            "type": "integer", 

            "format": "int32" 

          }, 

          { 

            "in": "query", 

            "name": "crmType", 

            "type": "string", 

            "enum": [ 

              "Salesforce", 

              "Dynamics365" 

            ] 

          }, 

          { 

            "in": "query", 

            "name": "crmOrgUrl", 

            "type": "string" 

          } 

        ], 

        "responses": { 

          "200": { 

            "description": "Success", 

            "schema": { 

              "$ref": "#/definitions/ActivityListResponseEnvelope" 

            } 

          }, 

          "400": { 

            "description": "Bad Request", 

            "schema": { 

              "$ref": "#/definitions/ApiError" 

            } 

          }, 

          "401": { 

            "description": "Unauthorized", 

            "schema": { 

              "$ref": "#/definitions/ApiError" 

            } 

          }, 

          "403": { 

            "description": "Forbidden", 

            "schema": { 

              "$ref": "#/definitions/ApiError" 

            } 

          }, 

          "404": { 

            "description": "Not Found", 

            "schema": { 

              "$ref": "#/definitions/ApiError" 

            } 

          }, 

          "429": { 

            "description": "Too Many Requests", 

            "schema": { 

              "$ref": "#/definitions/ApiError" 

            } 

          }, 

          "500": { 

            "description": "Server Error", 

            "schema": { 

              "$ref": "#/definitions/ApiError" 

            } 

          } 

        }, 

        "x-ms-openai-data": { 

          "openai-enabled": true 

        } 

      } 

    }, 

    "<your API path goes here>": { 

      "get": { 

        "tags": [ 

          "Documents" 

        ], 

        "operationId": "scp-get-related-records", 

        "produces": [ 

          "application/json" 

        ], 

        "parameters": [ 

          { 

            "in": "query", 

            "name": "recordType", 

            "required": true, 

            "type": "string", 

            "enum": [ 

              "account", 

              "opportunity" 

            ] 

          }, 

          { 

            "in": "query", 

            "name": "recordId", 

            "required": true, 

            "type": "string" 

          }, 

          { 

            "in": "query", 

            "name": "top", 

            "type": "integer", 

            "format": "int32" 

          }, 

          { 

            "in": "query", 

            "name": "skip", 

            "type": "integer", 

            "format": "int32" 

          }, 

          { 

            "in": "query", 

            "name": "crmType", 

            "type": "string", 

            "enum": [ 

              "Salesforce", 

              "Dynamics365" 

            ] 

          }, 

          { 

            "in": "query", 

            "name": "crmOrgUrl", 

            "type": "string" 

          } 

        ], 

        "responses": { 

          "200": { 

            "description": "Success", 

            "schema": { 

              "$ref": "#/definitions/DocumentRecordListResponseEnvelope" 

            } 

          }, 

          "400": { 

            "description": "Bad Request", 

            "schema": { 

              "$ref": "#/definitions/ApiError" 

            } 

          }, 

          "401": { 

            "description": "Unauthorized", 

            "schema": { 

              "$ref": "#/definitions/ApiError" 

            } 

          }, 

          "403": { 

            "description": "Forbidden", 

            "schema": { 

              "$ref": "#/definitions/ApiError" 

            } 

          }, 

          "404": { 

            "description": "Not Found", 

            "schema": { 

              "$ref": "#/definitions/ApiError" 

            } 

          }, 

          "429": { 

            "description": "Too Many Requests", 

            "schema": { 

              "$ref": "#/definitions/ApiError" 

            } 

          }, 

          "500": { 

            "description": "Server Error", 

            "schema": { 

              "$ref": "#/definitions/ApiError" 

            } 

          } 

        }, 

        "x-ms-openai-data": { 

          "openai-enabled": true 

        } 

      } 

    } 

  }, 

  "definitions": { 

    "Activity": { 

      "required": [ 

        "dateTime", 

        "description", 

        "title" 

      ], 

      "type": "object", 

      "properties": { 

        "title": { 

          "minLength": 1, 

          "type": "string" 

        }, 

        "description": { 

          "minLength": 1, 

          "type": "string" 

        }, 

        "dateTime": { 

          "format": "date-time", 

          "type": "string" 

        }, 

        "url": { 

          "type": "string" 

        }, 

        "additionalProperties": { 

          "type": "object", 

          "additionalProperties": { 

            "type": "string" 

          } 

        } 

      } 

    }, 

    "ActivityListResponseEnvelope": { 

      "type": "object", 

      "properties": { 

        "value": { 

          "type": "array", 

          "items": { 

            "$ref": "#/definitions/Activity" 

          } 

        }, 

        "hasMoreResults": { 

          "type": "boolean" 

        } 

      } 

    }, 

    "ApiError": { 

      "required": [ 

        "errorCode" 

      ], 

      "type": "object", 

      "properties": { 

        "errorCode": { 

          "minLength": 1, 

          "type": "string" 

        }, 

        "errorMessage": { 

          "type": "string" 

        }, 

        "activityId": { 

          "type": "string" 

        }, 

        "details": { 

          "type": "object", 

          "additionalProperties": {} 

        } 

      } 

    }, 

    "DocumentRecord": { 

      "required": [ 

        "recordId", 

        "recordTitle", 

        "recordType", 

        "recordTypeDisplayName", 

        "recordTypePluralDisplayName" 

      ], 

      "type": "object", 

      "properties": { 

        "recordId": { 

          "minLength": 1, 

          "type": "string" 

        }, 

        "recordTypeDisplayName": { 

          "minLength": 1, 

          "type": "string" 

        }, 

        "recordTitle": { 

          "minLength": 1, 

          "type": "string" 

        }, 

        "recordTypePluralDisplayName": { 

          "minLength": 1, 

          "type": "string" 

        }, 

        "recordType": { 

          "minLength": 1, 

          "type": "string" 

        }, 

        "url": { 

          "type": "string" 

        }, 

        "additionalProperties": { 

          "type": "object", 

          "additionalProperties": { 

            "type": "string" 

          } 

        } 

      } 

    }, 

    "DocumentRecordListResponseEnvelope": { 

      "type": "object", 

      "properties": { 

        "value": { 

          "type": "array", 

          "items": { 

            "$ref": "#/definitions/DocumentRecord" 

          } 

        }, 

        "hasMoreResults": { 

          "type": "boolean" 

        } 

      } 

    } 

  } 

}